### ISSUE TITLE
HTML tags in course titles not rendered

### ISSUE THREAD

**Issue by ErikBoesen** [coursetable/coursetable#106]
This is an interesting issue—the simple approach to fixing it would mean *theoretically* that you could inject arbitrary HTML into the page via course title (obviously that'd never happen, but it's something to think about in terms of application design in general), so we might have to think this over a bit. As far as I can tell, `<i>` tags are the only ones that are used in course titles.
<img src="https://user-images.githubusercontent.com/5923662/75845034-ddc6c600-5da5-11ea-8ee5-f29477328e20.png">

**Comment by hsheth2** [comment]
One other potential solution, though likely overkill, would be to send the content through an HTML sanitizer, similar to what is done by email clients when they render HTML email. 

I'm in favor of simply manually checking for and processing `<i>` tags, unless we find more instances of this issue.
