### ISSUE TITLE
Allow users to choose a section to add to their worksheet

### ISSUE THREAD

**Issue by ErikBoesen** [coursetable/coursetable#1248]
**Is your feature request related to a problem? Please describe.**
Right now, keeping track of what section to go to for classes one is shopping is a problem that CourseTable doesn't presently solve. It would be nice if we could find a way to make sections trackable on the worksheet. As someone that always shops quite a few classes (currently I have 9 that I'm shopping) before refining down to a reasonable number, I don't necessarily want to take the time to put them all into my gcal before I know which ones I'll be sticking with.

**Describe the solution you'd like**
An ability to choose one of the sections of a class you've added to your worksheet and also have that section be shown on the worksheet.

**Describe alternatives you've considered**
Manually tracking what sections you're signed up for in Google Calendar or mentally

**Additional context**
N/A

**Comment by Josh-Cena** [comment]
We already list sections as courses.
