### ISSUE TITLE
Bundle size checker

### ISSUE THREAD

**Issue by Josh-Cena** [coursetable/coursetable#1348]
We currently include many packages in frontend—even lodash! We should see which packages are taking the most bandwidth and consider cutting down on the number of utilities we use (for example, who thinks we need both styled-components and CSS modules, and bootstrap on top)?

**Comment by neilsong** [comment]
+1

**Comment by Josh-Cena** [comment]
I am currently using this: bunx vite-bundle-visualizer

**Comment by Josh-Cena** [comment]
First PR created! https://github.com/coursetable/coursetable/pull/1482
