### ISSUE TITLE
Open Discussion on "Add {x}" UI/UX

### ISSUE THREAD

**Issue by neilsong** [coursetable/coursetable#1403]
# Description
 - This is just a centralized place for preliminary thoughts and brainstorming that you can contribute to over break. Any comment is helpful, so feel free to join in!
 - With that in mind, the overarching idea is that we can reference this issue in a more formal discussion at the Monday meeting after break
 - We probably will consult a designer, and this will be a good resource for them to draw upon.

# Initial Thoughts

This section will be a fleshed out extension of what I briefly described in my comment in #1402. For context, my preferred design pattern is Material UI, and much of my design choices follow the opinions of that framework. 

## Dropdown
The idea is that we consolidate all "Add {x}" workflows into one button dropdown. This should, following convention, be placed right aligned in the menubar, next to the light/dark mode icon.

Here is rough visual of what the action button dropdown will look like for outline purposes:
![image](https://github.com/coursetable/coursetable/assets/67600593/8cf92b72-2d87-47ef-9722-4972a1f69bc2)

## Dialog
Whenever the actual "Add {x}" option is pressed, a reusable general "Add {x}" dialog (modal-style) component will be opened.

Here is a rough visual of what the dialog component will look like for outline purposes:
![image](https://github.com/coursetable/coursetable/assets/67600593/39a7e885-fa19-454e-b5d8-6c9a06c3c404)

## onAddClick

Functional logic wise, we implement the following steps:

### Form Validation

> Self-explanatory, but make sure to **implement invalid input callbacks.** (like outline the text field field red)

### Loading

> **Something that we lack critically are loaders, so I will add a loader visualization for completion's sake:**
> ![Peek 2023-11-16 13-58](https://github.com/coursetable/coursetable/assets/67600593/ea0f5c92-4dc2-4946-8424-ec60c0946cc0)

### Request

> Self-explanatory, but make sure to **implement failed request callbacks.** (like "Something went wrong" message)

# Edits

## 1: Benefits
The biggest pro (imo) of this approach: modularity and reusability. I believe this approach is de-facto for the "add" action. The "rename" and "remove" action all have information dependency on existing items, so they should be implemented within the respective list views.

**Comment by Josh-Cena** [comment]
I don't think it makes sense to have "Add friend" and "add worksheet" under the same dropdown—they are orthogonal actions and shouldn't be conflated. I think it would make more sense to have "Friends" and "Worksheets" each be a dropdown: whenever you open a dropdown, you have a text input for addition, and each item in the list has an associated button for deletion.

**Comment by neilsong** [comment]
I think your approach makes more sense.

My only comment would be that instead of just a text input for addition, we do a similar add button -> modality approach since the dropdown already has a lot of text fields. I also think that the entire concept of active item component at the top is flawed, since the deep blue highlight should be enough.

What are your thoughts in implementing an editable rename state on item double-click?

Agreed with the deletion workflow.

Rename and deletion should each have loaders replacing action icons/buttons within the item itself.

**Comment by Josh-Cena** [comment]
TBH, I don't fancy the idea of modals in general—they are hard to be implemented correctly and accessibly. A simple text input should suffice, but your reasoning is fine too.

**Comment by bearsyankees** [comment]
@CilantroMalik @wesleyandrade05 will try and tackle this this semester (both being only semi present due to courseload)

**Comment by Josh-Cena** [comment]
The UI has been redesigned now
