### ISSUE TITLE
Have URL previews of course links show course detail

### ISSUE THREAD

**Issue by bearsyankees** [coursetable/coursetable#1430]
## Problem

If you text someone a course, they can't see the course title or any metadata until they click and sign in. However, course info, such as title and professor, are public info and do not need cas auth.
## Proposed solution
Serverless? Need to somehow dynamically encode the course title in the <head> of the page that is shared. And must be done server-side (I think) bc the bots that scrape the info for url previews can't execute JS. But I don't have a clear plan....

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/coursetable/coursetable/pull/1642!
