### ISSUE TITLE
Display course titles when browsing previous evaluations

### ISSUE THREAD

**Issue by kevinhu** [coursetable/coursetable#147]
On the legacy site, browsing past evaluations for a course shows the course titles, which can be informative when the past evaluations are for a different course.

Legacy:
<img width="473" alt="Screen Shot 2020-10-19 at 10 18 47 PM" src="https://user-images.githubusercontent.com/6051736/96532123-2f4e9300-1259-11eb-8b0b-a13b652967bd.png">

Current:
<img width="436" alt="Screen Shot 2020-10-19 at 10 19 14 PM" src="https://user-images.githubusercontent.com/6051736/96532101-265dc180-1259-11eb-8d4a-6bdead7b205e.png">

**Comment by maxyuan6717** [comment]
TODO
-Update modal header to this format for past courses:

Course Title (season)
Course Code | Professor | Section | Skills/Areas
