### ISSUE TITLE
Worksheet list/timetable should refresh automatically

### ISSUE THREAD

**Issue by pxpeterxu** [coursetable/coursetable#15]
In GitLab by @ErikBoesen on Sep 12, 2019, 12:13

While using the worksheet list/timetable view this semester, I found myself getting pestered by the way that when I removed an item from my worksheet, I had to refresh or go to another panel then return to the calendar before that course would disappear from the sheet. I think this should occur automatically.

**Comment by hsheth2** [comment]
Switching between list and timetable should also trigger a save/refresh.
