### ISSUE TITLE
Store worksheet course hidden status & color in DB

### ISSUE THREAD

**Issue by Josh-Cena** [coursetable/coursetable#1527]
This should allow us to fix https://github.com/coursetable/coursetable/issues/1441 & https://github.com/coursetable/coursetable/issues/1443

**Comment by bearsyankees** [comment]
@Josh-Cena do we want to also still use local storage for hidden courses, or just use completely rely on db for it?

**Comment by Josh-Cena** [comment]
Let's completely rely on DB. You have to use the DB to get the list anyway.

**Comment by Josh-Cena** [comment]
https://github.com/coursetable/coursetable/pull/1661 starts the effort

**Comment by Josh-Cena** [comment]
Going to close this and track the rest in https://github.com/coursetable/coursetable/issues/1441
