### ISSUE TITLE
Prof history should collapse cross-listings

### ISSUE THREAD

**Issue by benzuzu** [coursetable/coursetable#1548]
## Problem

Right now the current modal's course only shows up in "both" out of the three categories (course, both, prof):
<img width="317" alt="Screenshot 2024-01-06 at 1 40 19 PM" src="https://github.com/coursetable/coursetable/assets/71607240/8c1f346e-65d1-49b1-bbad-a1c3008e7a0d">

This can get confusing. For the above example, it seems like the course has never been offered before. Also, for courses with different professors throughout semesters, the iterations taught by the current modal's professor will not show up in the "course" category, and it's not as easy to compare the professor's ratings compared to others. 

And say, for an example where the course is the only course the professor has taught, the "prof" category would have 0 courses and it would seem like the professor has never taught a course before.

Another issue is that cross-listed courses will appear multiple times in the "prof" category. So usually the course modal's course will not show up in the "prof" category, but if the course is cross-listed, it will should up 1 to 3 times in the "prof" category depending on how many cross-listings there are.

## Proposed solution

The current modal's course should show up in all three categories, and cross-listed courses should not show up in the "prof" category.

**Comment by Josh-Cena** [comment]
Will be fixed by https://github.com/coursetable/coursetable/pull/1545

**Comment by Josh-Cena** [comment]
Fixed in https://github.com/coursetable/coursetable/commit/6a8a2fde928aad843cf4e68b54b8ac7b4badf9bc, but the cross-listed courses in "prof" is still unfixed.
