### ISSUE TITLE
Search improvements

### ISSUE THREAD

**Issue by hsheth2** [coursetable/coursetable#156]
- [x] Add ability to change sort order (asc or desc) in search
- [x] Default search to order by course code
- [x] Remove the "relevance" option for now
- [x] Add department search
- [ ] Add ability to search/filter by day and time of day

**Comment by hsheth2** [comment]
I have made it so that searching "PLSC" only returns courses in that department - is that enough?

**Comment by maxyuan6717** [comment]
It works well in the general case that the department acronym isn't an actual word, but for MATH, for example, u get courses from other departments cuz math appears in the description. Not sure if ppl are more picky
