### ISSUE TITLE
Audit Ferry computed_listing_info fields that we don't use

### ISSUE THREAD

**Issue by Josh-Cena** [coursetable/coursetable#1607]
I first used this query to collect all fields:

```graphql
{
  __type(name: "computed_listing_info") {
    fields {
      name
    }
  }
}
```

And then find the ones we don't use:

```ts
import { spawnSync } from 'child_process';

const fields = response.data.__type.fields.map((field) => field.name);

for (const field of fields) {
  const { status, stdout, stderr } = spawnSync(`git`, [
    'grep',
    field,
    '--',
    ':!frontend/src/generated',
  ]);
  if (status !== 0) {
    console.error(`${field} Error: ${status}`);
    console.error(stderr.toString());
  } else {
    if (stdout.toString().split('\n').length < 5) {
      console.log(stdout.toString());
    }
  }
}
```

In the end I found that the following aren't even in our catalog query:

- `average_rating_n`
- `average_rating_same_professors_n`
- `average_workload_n`
- `average_workload_same_professors_n`
- `declined`
- `last_enrollment_course_id`
- `last_enrollment_season_code`
- `no_response`

The following aren't used beyond the query:

- `last_offered_course_id`
- `listing_id`
- `same_course_and_profs_id`

In addition, there are `colsem` and `sysem`, but I think they can be useful (such as https://github.com/coursetable/coursetable/issues/1455). But for the ones above, we should see whether we actually need this data. I think the different IDs are useful for course relationships (https://docs.google.com/document/d/1mIsanCz1U3M6SU2KbcBp9ONXRssDfeTzRtDIRzxdAOk), but for the others they are probably legacy.

**Comment by Josh-Cena** [comment]
@neilsong Maybe you want to do this as part of your Ferry rewrite?

**Comment by neilsong** [comment]
Ok - I will see if we can drop these data computation steps in ferry. Thanks for letting me know 👍

**Comment by Josh-Cena** [comment]
`computed_listing_info` is now legacy and unused. We'll remove this table altogether later.
