### ISSUE TITLE
Hardcode courses that shouldn't be linked

### ISSUE THREAD

**Issue by bearsyankees** [coursetable/coursetable#1625]
example cpsc 427 is no longer OOP but it retains those attributes (it shouldn't)

**Comment by Josh-Cena** [comment]
This seems to have fixed itself. In fact, Ferry has always had the capability to unlink recycled course codes with different content based on title/description matching: https://github.com/coursetable/ferry/blob/v1/docs/3_same_classes.md so CPSC 427 displaying OOP must have been a frontend bug.
