### ISSUE TITLE
Scrolling Bug on Windows 10, Chrome 122, course listing blackout

### ISSUE THREAD

**Issue by Redorhcs** [coursetable/coursetable#1628]
## Bug description

Scrolling to the bottom of a coursetable course listing, then returning to the top, will cause the courses view to black out.

## Reproduction

1. Go to https://coursetable.com/catalog
2. Search for any valid value or filter by department (CPSC)
3. Scroll down to the very bottom, and attempt to scroll back up

## Expected behavior

[Video - sharepoint/internal](https://yaleedu-my.sharepoint.com/:v:/g/personal/tyler_schroder_yale_edu/Ee4E_TIJ1dJGrbf62wvuQtEBlST_26UD07iMVlEAXDGI0Q?e=ONLikr)

## Environment

For desktop:

- OS: Windows 10 Education, 22H2
- Browser: Chrome
- Version: 122.0.6261.95 (Official Build) (64-bit) (cohort: Stable) 
- uBlock Origin installed (replicated even when disabled/uninstalled)

**Comment by Josh-Cena** [comment]
Thanks for the report. Unfortunately I can't reproduce it on my Chrome 122, macOS. Maybe it's Windows specific.

**Comment by Redorhcs** [comment]
@Josh-Cena Can you jump into a windows desktop on myapps.yale.edu? I am able to replicate in MyApps as seen in screenshot below. MyApps is running 122.0.6261.95 (Official Build) (64-bit) (cohort: Stable) Win10 Enterprise 22H2
<img width="950" alt="2024-03-05 16_49_02-Yale Desktop" src="https://github.com/coursetable/coursetable/assets/11656073/a34a3309-2fb1-42c1-98c7-dc40d8514c31">

**Comment by Josh-Cena** [comment]
Wow, TIL this is a thing! Unfortunately I cannot reproduce it on MyApps either. Let's confirm: does it happen with every kind of scrolling (i.e. trackpad, mouse, using the scrollbar)? Have you checked if your friends have the same issue (since you can show this to them real-time)?

**Comment by Redorhcs** [comment]
I've got at least one other win10 22h2 user impacted, can send names/netids offline if that's of interest. Happens with any method of scrolling. If you consult this photo - a second inner scroll bar appears just before we hit the bottom, and at the bottom of the exterior scroll is when we get the blackout. It comes back after scrolling up, but glitches a bit on the way. This happens in both my laptop/MYApp, and one friend is able to repro locally. 
<img width="242" alt="2024-03-05 19_14_12-E2 Readings - OneNote" src="https://github.com/coursetable/coursetable/assets/11656073/299e8730-22fd-4314-8953-6de0c8507b61">

Let me know if anything else is helpful (Extra recordings, HAR files) and I'd be happy to provide.

**Comment by Redorhcs** [comment]
Still occurring on Chrome 123, Win 10. Double scroll bar appears at bottom, then goes black on scrollup.

<img width="960" alt="2024-03-28 16_52_52-Outlook Today - Outlook" src="https://github.com/coursetable/coursetable/assets/11656073/99bb8a3f-ca42-46a1-9158-8b366a5aa488">

**Comment by Josh-Cena** [comment]
I think I understand what's going on now— @Redorhcs could you confirm that it only happens when the browser is not full screened? I can only reproduce this on MyApps with the browser not full screened, otherwise there's no double scrollbar.

Also, thank you for blurring out the ratings—that's really considerate.

**Comment by Josh-Cena** [comment]
I can also now reproduce it on my Mac, with the window slightly narrower than 1440px wide, although it doesn't have to be as narrow as a tablet screen.

**Comment by Redorhcs** [comment]
@Josh-Cena  Happens with or without fullscreen on Windows at least. My laptop is smaller than most macbooks (14in) fwiw. Great to hear you can replicate - let me know if more info is needed

**Comment by Josh-Cena** [comment]
My Mac is 13.3in. In your screen 1440px wide, or less?

**Comment by Redorhcs** [comment]
Misread on system specs - 13.3" WUXGA (1920 x 1200) IPS

**Comment by Josh-Cena** [comment]
So I spent two hours trying to fix the issue that I can reproduce on my device. I know _why_ it happens, but I still don't know _how_ it happens. Will keep you posted.

**Comment by Redorhcs** [comment]
Window InnerWidth is `758 < X < 1300` trying different lengths. Replicable at 758

**Comment by Josh-Cena** [comment]
Thanks, yeah I can reproduce it at lower widths too, just not above 1320. What happens if you zoom out (<kbd>Ctrl</kbd> + <kbd>-</kbd>) twice? This should make your window larger than the physical size.

**Comment by Josh-Cena** [comment]
@Redorhcs A fix is deployed. Could you check if it fixes the issue? Thanks for the detailed follow-ups!

**Comment by Redorhcs** [comment]
@Josh-Cena - much better! Quick video linked on sharepoint if helpful for my view - there was a very very brief flutter at one point but it's much less jarring / UX impacting compared to what was. https://yaleedu-my.sharepoint.com/:v:/g/personal/tyler_schroder_yale_edu/ESu1tVqzVKxNh8dzNmsDXSgBWf2Ntpqln0GQn9YmtaK6mw?e=Ef7l4n
