### ISSUE TITLE
Select Course(s) not registering as course/credit in worksheet summary

### ISSUE THREAD

**Issue by Redorhcs** [coursetable/coursetable#1678]
## Bug description

GLBL 283 "Technology and War" does not register as a for-credit course, causing a six-credit worksheet to register as a five-credit worksheet in summary view. Course has been previously taught for credit at Yale.

## Reproduction

Go to course search, look for GLBL 283, add to any worksheet, see summary as 0 credit

<img width="944" alt="2024-04-09 14_17_02-Inbox - tyler schroder@yale edu - Outlook" src="https://github.com/coursetable/coursetable/assets/11656073/6929bc52-e9c6-44dc-aa9c-3570fe141422">

## Expected behavior

Course with 1 credit weight and previous reviews would factor in correctly in summary

## Environment

For desktop:

- OS: Windows 10 22H2
- Browser: Chrome
- Version: 123.0.6312.106 (Official Build) (64-bit) (cohort: Stable)

**Comment by Josh-Cena** [comment]
Should it be one credit, or is it actually no credit?

**Comment by Josh-Cena** [comment]
Looks like it's actually listed as 0 credits on YCS. I think we should find a better heuristic, so this course is still counted towards other statistics. We currently use "no credit" as the heuristic to exclude potential duplicates like class + discussions.

**Comment by Redorhcs** [comment]
Just seeing that as 0 credits - oops, didn’t notice prior. I would still expect it to count towards the classes counter, instead of neither. On Apr 9, 2024, at 14:48, Joshua Chen ***@***.***> wrote:﻿
Looks like it's actually listed as 0 credits on YCS. I think we should find a better heuristic, so this course is still counted towards other statistics. We currently use "no credit" as the heuristic to exclude potential duplicates like class + discussions.

**Comment by Josh-Cena** [comment]
I have hopefully implemented a better strategy in https://github.com/coursetable/coursetable/commit/897d973367fbfbde11285b659345f7b1557ff12c. There are way too many edge cases of this UX to consider

**Comment by Redorhcs** [comment]
Thanks so much!

v/r
Tyler Schroder

—
Tyler Schroder NT1S, CSAP
***@***.***
C 703-939-0494
________________________________
From: Joshua Chen ***@***.***>
Sent: Tuesday, April 9, 2024 3:17:09 PM
To: coursetable/coursetable ***@***.***>
Cc: Tyler S. ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [coursetable/coursetable] Select Course(s) not registering as course/credit in worksheet summary (Issue #1678)


I have hopefully implemented a better strategy in 897d973<https://github.com/coursetable/coursetable/commit/897d973367fbfbde11285b659345f7b1557ff12c>. There are way too many edge cases of this UX to consider

**Comment by Redorhcs** [comment]
Hey @Josh-Cena this is a YCS issue I'll email my AA about. The cross-list in PLSC (145) says 1 credit, but the glbl code says 0 credit. So I think the root cause is not a coursetable issue, but thanks for the update as well as that makes it more clear on the stats.

**Comment by Josh-Cena** [comment]
Yeah no prob! I was quite surprised that no-credit "real" classes existed ^^
