### ISSUE TITLE
Search and sorting across written evaluations

### ISSUE THREAD

**Issue by kevinhu** [coursetable/coursetable#192]
Currently, evaluations are displayed in arbitrary order, which makes reading through them all difficult, especially for the larger lecture-based classes.

The previous site allows users to order evaluations by length. In addition to length ordering, we now have evaluation sentiment scores to sort by as well. These are listed for all written evaluations under the `comment_compound` field in the `evaluation_narratives` table as numerical values, with more positive ones indicating more positive responses.

In addition, we can add client-side full-text search over evaluations using libraries such as [FlexSearch](https://github.com/nextapps-de/flexsearch) (ridiculously fast).

**Comment by Josh-Cena** [comment]
We now have both. The other functions are tracked in https://github.com/coursetable/coursetable/issues/115 and #656
