### ISSUE TITLE
Add a "last updated" timestamp with the time of the last successful ferry crawler run

### ISSUE THREAD

**Issue by hsheth2** [coursetable/coursetable#351]

**Comment by itsjoshthedeveloper** [comment]
superseded by #436

**Comment by itsjoshthedeveloper** [comment]
actually on second thought, might be better to keep this open as a separate issue since it requires info from ferry

**Comment by Josh-Cena** [comment]
Fixed by https://github.com/coursetable/coursetable/commit/038318eea0cd6f46173ffd4ffbb2e2c51bfdf749, https://github.com/coursetable/coursetable/commit/8676ac899fe818586bfa7f03593495ccb2c8f28c, https://github.com/coursetable/ferry/commit/f081f25054ba7073e003ecce72b719b720e67565
