### ISSUE TITLE
link a past course's syllabi/course modal page on the course eval page for a past course

### ISSUE THREAD

**Issue by joshuachough** [coursetable/coursetable#358]
Description: Since many class syllabi have changed this year, some of them don't quite match what course reviews are saying (ie. there might have been a final in a previous semester instead of what is now a research paper, etc.). Because of that, it could be helpful to have past syllabi linked to that semester's evaluations just for easier reference.

**Comment by Josh-Cena** [comment]
We already have this via the "More info" button now.
