### ISSUE TITLE
Replace graphqurl in API

### ISSUE THREAD

**Issue by kevinhu** [coursetable/coursetable#364]
**Problem**: we currently use [graphqurl](https://github.com/hasura/graphqurl) in our API server to fetch aggregate course JSONs as well as data for challenges, but this library is not supported well.

We could instead use apollo-client like we do on the frontend. There's a few differences in the setup, but it should be relatively easy. See [this tutorial](https://learn.vonage.com/blog/2020/03/12/using-apollo-to-query-graphql-from-node-js-dr#) for an example.

**Comment by hsheth2** [comment]
This should also allow us to use graphql-codegen with typescript + Apollo bindings, similar to the current setup in the frontend

**Comment by hsheth2** [comment]
Seems like graphql-request is also a good and simple option: https://www.npmjs.com/package/graphql-request

It also has integrations with graphql-codegen https://graphql-code-generator.com/docs/plugins/typescript-graphql-request

**Comment by kevinhu** [comment]
graphql-request looks much cleaner than apollo-client – I'll try both of them out with the course JSON fetching first to compare.
