### ISSUE TITLE
Cannot find module 'levenary'

### ISSUE THREAD

**Issue by itsjoshthedeveloper** [coursetable/coursetable#443]
when running `docker-compose up` on the master branch, i get this error

![image](https://user-images.githubusercontent.com/34778271/104072879-5ecac700-51da-11eb-80dd-647838b9c557.png)

**Comment by itsjoshthedeveloper** [comment]
nevermind think i messed up docker.. deleting and cloning the repository fixed it

**Comment by hsheth2** [comment]
Nice - in general, running `docker-compose restart` often fixes these types of problems, since it refreshes the dependencies and reinstalls as necessary.
