### ISSUE TITLE
UI: Sync changes between cross-listed courses

### ISSUE THREAD

**Issue by pxpeterxu** [coursetable/coursetable#5]
In GitLab by @hsheth2 on Sep 5, 2019, 20:30

For example, assume a class is listed as both CPSC 235 and EENG 245. If a user adds CPSC 235 to their worksheet, then the EENG 245 entry should indicate that it was already added via a cross listing. 

How exactly this should behave is still up for debate. It's also unclear if this would require any changes to the backend.

**Comment by hsheth2** [comment]
Closed in favor or #96.
