### ISSUE TITLE
Show course conflict icon even when scrolling

### ISSUE THREAD

**Issue by achrysaetos** [coursetable/coursetable#643]
Just a minor improvement. Currently, when the user scrolls through the search results, the course conflict icon disappears, then reappears when the user stops scrolling. We want to keep showing the course conflict icon until it is past the window, for smoother action.

**Comment by maxyuan6717** [comment]
Oh I made it disappear on scroll to improve scroll performance but you can try implementing it while maintaining performance!

**Comment by achrysaetos** [comment]
is there a way of measuring the performance? I didn't really notice any difference when I removed it.
