### ISSUE TITLE
Automatically sync CourseTable worksheets with calendars

### ISSUE THREAD

**Issue by kevinhu** [coursetable/coursetable#652]
**Is your feature request related to a problem? Please describe.**
Right now, our calendar export feature requires the user to click the "Export Worksheet" button to generate an .ics file everytime they want to update their calendars.

**Describe the solution you'd like**
Host the .ics calendars ourselves, so Google Calendar / whatever can auto update them without any user intervention.
In particular:
- Each user's worksheet is pushed to a .ics file in our public static directory in the API, probably with a hashed filename so you can't view anybody's worksheet. Users can sync their calendar simply by using a link in the format of `https://calendar.google.com/calendar/r?cid=webcal://<LINK_TO_ICS>`
- Every time a user modifies their worksheet, we update their calendar
- Every time classes are crawled, we update everybody's calendar

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by benzuzu** [comment]
https://github.com/coursetable/coursetable/pull/1379

we use gcal api to actually modify user's default calendar instead. live updating may be a bit overkill, but definitely something to consider
