### ISSUE TITLE
Add switch to toggle discussion sections

### ISSUE THREAD

**Issue by maxyuan6717** [coursetable/coursetable#659]
**Is your feature request related to a problem? Please describe.**
People find the discussion sections annoying in the catalog.

**Describe the solution you'd like**
Add a toggle to show/hide them

**Describe alternatives you've considered**
Just deleting them?

**Comment by achrysaetos** [comment]
I implemented this in my courses-on-modal branch, pull request https://github.com/coursetable/coursetable/pull/640.
