### ISSUE TITLE
Clean up `console.log`s in frontend

### ISSUE THREAD

**Issue by kevinhu** [coursetable/coursetable#675]
We've got a bunch of console statements in the frontend that shouldn't be there: https://github.com/coursetable/coursetable/search?q=console

For the ones that are used to catch errors, we should use Sentry instead (as in `Sentry.captureException(error)`)

**Comment by kevinhu** [comment]
It catches errors and notifies us when they occur – check your email for an invite

**Comment by itsjoshthedeveloper** [comment]
Gotcha does this include dev localhost errors? Or just production?

**Comment by kevinhu** [comment]
I think both for now, we just haven't disabled the dev ones yet
