### ISSUE TITLE
Make Facebook toggles more user-friendly

### ISSUE THREAD

**Issue by kevinhu** [coursetable/coursetable#676]
Right now, the Facebook disconnect button also has the refresh icon right next to it, which makes misclicks pretty easy. We should try to separate these, for instance by moving the refresh button to it's own row.

<img width="196" alt="Screen Shot 2021-04-08 at 14 15 12" src="https://user-images.githubusercontent.com/6051736/114097448-e3c68a80-9874-11eb-8e4e-0ca66663756d.png">

**Comment by itsjoshthedeveloper** [comment]
I separated these and put the refresh button on the worksheet navbar and the disconnect in the dropdown. Does that work? @kevinhu

**Comment by kevinhu** [comment]
Yep!
