### ISSUE TITLE
Add Link to Building Location

### ISSUE THREAD

**Issue by codyjlin** [coursetable/coursetable#69]
For building locations, users might want to more conveniently see where a class meets instead of having to go search on google or the campus map. We could take the building codes from the location tab for a class and parse with the url pattern below:

Examples:
- https://map.yale.edu/place/building/AKW
- https://map.yale.edu/place/building/LEPH

Some that don't work:
- CO451 on Coursetable, but should be looked up as COLL451 (https://map.yale.edu/place/building/CO451 vs https://map.yale.edu/place/building/COLL451)
- LEIGH on Coursetable, but should be looked up as LGH
(https://map.yale.edu/place/building/LEIGH vs https://map.yale.edu/place/building/LGH)

It might be safer to just use this url, to bring up search results for building rather than assume correct building:
- https://map.yale.edu/search/CO451/15/41.31118/-72.92579
- https://map.yale.edu/search/LEIGH/15/41.31118/-72.92579

**Comment by hsheth2** [comment]
Building abbreviations data is listed at http://catalog.yale.edu/ycps/building-abbreviations/.
